apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/xfy0012/techtrends
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
      - values-prod.yaml
  project: default
